### PR TITLE
fix exit code and report result to test-store

### PR DESCRIPTION
**Pull request by zyguan**
Let the test case report its results, see:
- https://testing.pingcap.net/api/v1/results/3
- http://172.16.4.180:31702/proxy/api/v1/namespaces/testground/pods/tikops-test-amend-random-4pjl9-test-7z2zh-pod-6p94x/log?container=step-test

### CODE REVIEW

**Comment by cfzjywxk** [comment]
Should the the result of api contain some pointers to the detailed failure package like jepsen tests, so that if the root cause of the test failure could not be tracked troghout it?
@you06 @zyguan

**Comment by zyguan** [comment]
> Should the the result of api contain some pointers to the detailed failure package like jepsen tests, so that if the root cause of the test failure could not be tracked troghout it?
> @you06 @zyguan

Yes, actually there is an `output` field which is for failure reason. I forgot to set it when test timeout (fixed by https://github.com/PingCAP-QE/amend-random/pull/10/commits/4e7779d9ce2054b3c8726530b576d21c075b4ca1) . We can also upload more info to the internal fileserver, like https://github.com/PingCAP-QE/tikops/blob/master/lib/tests/amend-random.libsonnet#L40-L44 .

**Comment by cfzjywxk** [comment]
LGTM

**Comment by zyguan** [comment]
@cfzjywxk @you06 Can we merge this PR?

**Review by you06 — APPROVED** [review]
LGTM

**Pull request merged**
